apiVersion: v1
name: qautomatron/docker-browsermob-proxy
version: 1.0.0
appVersion: 2.1.3
description: Chart for mobproxy
keywords:
- qa
home: http://www.seleniumhq.org/
icon: http://bmp.lightbody.net/images/zip-icon.png
sources:
- https://github.com/SeleniumHQ/docker-selenium
maintainers:
- name: palmer
  email: chenghaoo@hotmail.com
engine: gotpl
