apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: browsermobproxy
  name: browsermobproxy
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  - name: "9191"
    port: 9191
    targetPort: 9191
  selector:
    io.kompose.service: browsermobproxy
status:
  loadBalancer: {}
