apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: browsermobproxy
  name: browsermobproxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: browsermobproxy
    spec:
      containers:
      - image: qautomatron/docker-browsermob-proxy:2.1.3
        name: browsermobproxy
        ports:
        - containerPort: 9090
        - containerPort: 9191
        resources: {}
      restartPolicy: Always
status: {}
