apiVersion: v1
kind: Service
metadata:
  annotations:
    io.rancher.scheduler.affinity:host_label: RANCHER_HOST_TYPE=MASTER
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: hub
  name: hub
spec:
  ports:
  - name: "4444"
    port: 4444
    targetPort: 4444
  selector:
    io.kompose.service: hub
status:
  loadBalancer: {}
