apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    io.rancher.scheduler.affinity:host_label: RANCHER_HOST_TYPE=MASTER
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: hub
  name: hub
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: hub
    spec:
      containers:
      - env:
        - name: CHROME
          value: "false"
        - name: FIREFOX
          value: "false"
        - name: GRID
          value: "true"
        - name: PULL_SELENIUM_IMAGE
          value: "true"
        - name: SELENIUM_CONTAINER_LABELS
          value: io.rancher.container.network=true
        - name: SELENIUM_HUB_HOST
          value: hub
        - name: SELENIUM_HUB_PORT
          value: "4444"
        - name: SELENIUM_WAIT_FOR_CONTAINER
          value: "true"
        - name: TZ
          value: Asia/Shanghai
        image: elgalu/selenium
        name: hub
        ports:
        - containerPort: 4444
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/shm
          name: hub-claim0
      restartPolicy: Always
      volumes:
      - name: hub-claim0
        persistentVolumeClaim:
          claimName: hub-claim0
status: {}
