apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    chart: browsermobproxy
  name: browsermobproxy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        chart: browsermobproxy
    spec:
      containers:
      - env:
        - name: PORT_RANGE
          value: 39500-39507
        image: qautomatron/docker-browsermob-proxy:latest
        name: browsermobproxy
        ports:
        - containerPort: 9090
        - containerPort: 39500
        - containerPort: 39501
        - containerPort: 39502
        - containerPort: 39503
        - containerPort: 39504
        - containerPort: 39505
        - containerPort: 39506
        - containerPort: 39507
        resources: {}
      restartPolicy: Always
status: {}
