apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  name: kafka2
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: kafka2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka2
    spec:
      nodeSelector:
        k3s.io/hostname: {{ .Values.kafkaNodeLabel }}
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: {{ .Values.kafkaBrokerHost }}
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://{{ .Values.kafkaBrokerHost }}:9092
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs
        - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
          value: "1195725900"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: wurstmeister/kafka:2.11-0.10.2.2
        name: kafka2
        ports:
        - containerPort: 9092
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /kafka/kafka-logs
          name: kafka2-claim0
      restartPolicy: Always
      volumes:
      - name: kafka2-claim0
        hostPath:
          path: /opt/kafka/kafka2.11
status: {}
