kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka2-claim0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/kafka/kafka2.11"
